export const getIslandFlag = (islandName: string | undefined): string => {
  if (!islandName) return '';
  const map: Record<string, string> = {
    'Antigua and Barbuda': '🇦🇬',
    'Saint Lucia': '🇱🇨',
    'The Bahamas': '🇧🇸',
    'Saint Vincent & the Grenadines': '🇻🇨',
    'Jamaica': '🇯🇲',
    'Trinidad & Tobago': '🇹🇹',
    'Grenada': '🇬🇩',
    'Guyana': '🇬🇾',
    'Saint Kitts and Nevis': '🇰🇳',
    'Montserrat': '🇲🇸',
    'Bermuda': '🇧🇲',
    'Belize': '🇧🇿',
    'Anguilla': '🇦🇮',
    'The Cayman Islands': '🇰🇾',
    'The British Virgin Islands': '🇻🇬',
    'Turks & Caicos Islands': '🇹🇨',
    'United States Virgin Islands': '🇻🇮',
    'Aruba': '🇦🇼',
    'Haiti': '🇭🇹',
    'Dominican Republic': '🇩🇴',
    'Puerto Rico': '🇵🇷',
    'Cuba': '🇨🇺',
    'Curaçao': '🇨🇼',
    'Suriname': '🇸🇷',
    'Barbados': '🇧🇧',
    'Dominica': '🇩🇲',
    'Saint Martin / Sint Maarten': '🇸🇽',
    'Guadeloupe': '🇬🇵',
    'Martinique': '🇲🇶',
    'Bonaire': '🇧🇶',
    'Saint Barthélemy': '🇧🇱',
    'Saba': '🇧🇶',
    'Sint Eustatius': '🇧🇶',
    'Saint Pierre and Miquelon': '🇵🇲',
    'The Grenadines': '🇻🇨',
    'Tortola': '🇻🇬',
    'Eleuthera': '🇧🇸',
    'Spanish Town': '🇯🇲',
    'Carriacou & Petite Martinique': '🇬🇩',
    'Navassa Island': '🇺🇸',
    'Andros': '🇧🇸',
    'Port Royal': '🇯🇲',
    'The Inagua Islands': '🇧🇸',
    'Barbuda': '🇦🇬',
    'Nevis': '🇰🇳',
    'Grand Bahama': '🇧🇸',
    'Exuma': '🇧🇸',
    'Saint Pierre': '🇵🇲',
    'Marie-Galante': '🇬🇵',
    'Abaco': '🇧🇸'
  };
  return map[islandName] || '';
};
